---
- name: install java and net-tools
  hosts: aws
  tasks:
    - name: update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install java 8
      apt: name=openjdk-8-jre-headless
    - name: Install net-tools
      apt: name=net-tools


- name: Download and unpack Nexus installer
  hosts: aws
  tasks:
    - name: Download Nexus
      get_url:   #downloads files from http, https to server
        url: https://download.sonatype.com/nexus/3/nexus-3.80.0-06-linux-x86_64.tar.gz
        dest: /opt/
      register: download_result
    
    - name: Check nexus folder stats
      stat:
        path: /opt/nexus
      register: stat_result
    # - debug: msg={{stat_result.stat.exists}}

    # - debug: msg={{download_result}}
    - name: Untar nexus installer
      unarchive:
        src: "{{download_result.dest}}"
        dest: /opt/
        remote_src: yes
      when: not stat_result.stat.exists
    
    - name: Find nexus folder
      find: 
        paths: /opt
        pattern: "nexus-*"
        file_type: directory
      register: find_result
    # - debug: msg={{find_result}}
    

    - name: Rename nexus folder
      shell: mv {{find_result.files[0].path}} /opt/nexus
      when: not stat_result.stat.exists
  
- name: Create nexus user to own nexus folders
  hosts: aws
  tasks:
    - name: Ensure nexus group
      group:
        name: nexus
        state: present
    - name: Create nexus user
      user:
        name: nexus
        group: nexus
    - name: Make nexus user owner of nexus folder
      file:
        path: /opt/nexus
        state: directory
        owner: nexus
        group: nexus
        recurse: yes
    - name: Make nexus user owner of sonatype-work folder
      file:
        path: /opt/sonatype-work
        state: directory
        owner: nexus
        group: nexus
        recurse: yes


- name: Start nexus with nexus user
  hosts: aws
  become: True
  become_user: nexus
  tasks:
    - name: Set run_as_user nexus
      lineinfile:
        path: /opt/nexus/bin/nexus
        regexp: "^run_as_user=''"
        line: run_as_user='nexus'
      # blockinfile:
      #   path: /opt/nexus/bin/nexus.rc 
      #   block: |
      #     run_as_user="nexus"
    - name: Start nexus
      command: /opt/nexus/bin/nexus start

- name: Verify nexus is running
  hosts: aws
  tasks:
    - name: Check with ps
      shell: ps aux | grep nexus
      register: app_status
    - debug: msg={{app_status.stdout_lines}}

    - name: Wait one minute
      pause:
        minutes: 1
  
    - name: Check with netstat
      shell: netstat -plnt
      register: app_status
    - debug: msg={{app_status.stdout_lines}}